import turtle
from turtle import *

rains = turtle.Turtle()
title("how she change me")
rains.color("blue","black")

rains.begin_fill()
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)      #turtle dimension for a square
rains.end_fill()


rains.penup()
rains.forward(50)
rains.pendown()
rains.color("blue","black")
rains.begin_fill()
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.end_fill()

rains.penup()
rains.forward(50)
rains.pendown()
rains.color("blue","black")
rains.begin_fill()
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.end_fill()

rains.penup()
rains.forward(50)
rains.pendown()
rains.color("blue","black")
rains.begin_fill()
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.end_fill()

rains.penup()
rains.forward(50)
rains.pendown()
rains.color("blue", "#B587E1")
rains.begin_fill()
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.end_fill()

rains.penup()
rains.forward(50)
rains.pendown()
rains.color("blue", "#B587E1")
rains.begin_fill()
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.end_fill()

rains.penup()
rains.forward(50)
rains.pendown()
rains.color("blue", "#B587E1")
rains.begin_fill()
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.end_fill()

rains.penup()
rains.forward(50)
rains.pendown()
rains.color("blue", "#B587E1")
rains.begin_fill()
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.left(90)
rains.forward(100)
rains.end_fill()


turtle.done()